---
- name: install tcpdump on RedHat
  yum:
    name: tcpdump
    state: latest
  when: ansible_distribution_major_version == "7"

- name: install tcpdump on RedHat
  dnf:
    name: tcpdump
    state: latest
  when: ansible_distribution_major_version == "8"

- name: restart tcpdump service
  service: "name=tcpdump state=restarted" 
