---
- name: install rsyslog on RedHat
  yum:
    name: rsyslog
    state: present
  when: ansible_distribution_major_version == "7"

- name: install rsyslog on RedHat
  dnf:
    name: rsyslog
    state: present
  when: ansible_distribution_major_version == "8"

- name: restart rsyslog service
  service: "name=rsyslog state=restarted" 
