---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydb-pv
  namespace: preprod
spec:
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/mydb-preprod"
 
