---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydb-pv-dev
  namespace: dev
spec:
  storageClassName: manual
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/mydb-dev"
 
