---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydb-pv-prod
  namespace: prod
spec:
  capacity:
    storage: 1.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/mydb-prod"
 
