---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydb-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 0.5Gi
